# Deep Learning A Z Regressão 1 valor - Automóveis

In [ ]:
!pip install tensorflow==2.16.1

Collecting tensorflow==2.16.1
  Downloading tensorflow-2.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (589.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (0.2.0)
Collecting h5py>=3.10.0 (from tensorflow==2.16.1)
  Downloading h5py-3.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 12.7 MB/s eta 0:00:00
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (18.1.1)
Collecting ml-dtypes~=0.3.1 (from tensorflow==2.16.1)
  Downloading ml_dtypes-0.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 52.6 MB/s eta 0:00:00
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (2.31.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.64.1)
Collecting tensorboard<2.17,>=2.16 (from tensorflow==2.16.1)
  Downloading tensorboard-2.16.2-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 60.5 MB/s eta 0:00:00
Collecting keras>=3.0.0 (from tensorflow==2.16.1)
  Downloading keras-3.4.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 49.4 MB/s eta 0:00:00
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (0.37.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.16.1) (1.25.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow==2.16.1) (0.43.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.0.0->tensorflow==2.16.1) (13.7.1)
Collecting namex (from keras>=3.0.0->tensorflow==2.16.1)
  Downloading namex-0.0.8-py3-none-any.whl (5.8 kB)
Collecting optree (from keras>=3.0.0->tensorflow==2.16.1)
  Downloading optree-0.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 22.6 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.16.1) (2024.6.2)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.17,>=2.16->tensorflow==2.16.1) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow==2.16.1) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.0.0->tensorflow==2.16.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.0.0->tensorflow==2.16.1) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow==2.16.1) (0.1.2)
Installing collected packages: namex, optree, ml-dtypes, h5py, tensorboard, keras, tensorflow
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Successfully uninstalled h5py-3.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.15.2
    Uninstalling tensorboard-2.15.2:
      Successfully uninstalled tensorboard-2.15.2
  Attempting uninstall: keras
    Found existing installation: keras 2.15.0
    Uninstalling keras-2.15.0:
      Successfully uninstalled keras-2.15.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.15.0
    Uninstalling tensorflow-2.15.0:
      Successfully uninstalled tensorflow-2.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.15.1 requires tensorflow<2.16,>=2.15, but you have tensorflow 2.16.1 which is incompatible.
Successfully installed h5py-3.11.0 keras-3.4.0 ml-dtypes-0.3.2 namex-0.0.8 optree-0.11.0 tensorboard-2.16.2 tensorflow-2.16.1

In [ ]:
import pandas as pd
import tensorflow as tf
import sklearn

In [ ]:
pd.__version__, tf.__version__, sklearn.__version__

('2.0.3', '2.16.1', '1.2.2')

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
# https://www.kaggle.com/datasets/vfsousas/autos
base = pd.read_csv('autos.csv', encoding = 'ISO-8859-1')
base

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [ ]:
base = base.drop('dateCrawled', axis = 1)
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)
base

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371524,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN
371527,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [ ]:
base['name'].value_counts()

name
Ford_Fiesta                                              657
BMW_318i                                                 627
Opel_Corsa                                               622
Volkswagen_Golf_1.4                                      603
BMW_316i                                                 523
                                                        ...
Audi_A4_Avant_Klima_Gruene_Plakette_TÜV_&AU_NEU_XENON      1
Renault_clio_in_gold_450VB_!!                              1
Fiat_Doblo_1.6_Multijet                                    1
Renault_Laguna_1                                           1
BMW_M135i_vollausgestattet_NP_52.720____Euro               1
Name: count, Length: 233531, dtype: int64

In [ ]:
base = base.drop('name', axis = 1)

In [ ]:
base['seller'].value_counts()

seller
privat        371525
gewerblich         3
Name: count, dtype: int64

In [ ]:
base = base.drop('seller', axis = 1)

In [ ]:
base['offerType'].value_counts()

offerType
Angebot    371516
Gesuch         12
Name: count, dtype: int64

In [ ]:
base = base.drop('offerType', axis = 1)

In [ ]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [ ]:
base.loc[base['price'] <= 10]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein
40,0,test,NaN,1990,NaN,0,corsa,150000,1,benzin,opel,NaN
60,1,control,suv,1994,manuell,286,NaN,150000,11,NaN,sonstige_autos,NaN
91,1,control,limousine,1995,manuell,113,e_klasse,150000,4,diesel,mercedes_benz,nein
115,0,test,NaN,2017,manuell,0,golf,5000,12,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371356,0,control,NaN,2000,manuell,65,corsa,150000,0,NaN,opel,ja
371392,0,test,kleinwagen,2002,manuell,60,fiesta,150000,3,benzin,ford,NaN
371402,0,control,kleinwagen,1999,manuell,53,swift,150000,3,benzin,suzuki,NaN
371431,0,control,kleinwagen,1999,manuell,37,arosa,150000,7,benzin,seat,ja
371522,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja

In [ ]:
base['price'].mean()

17295.14186548524

In [ ]:
base = base[base['price'] > 10]

In [ ]:
base.shape

(359410, 12)

In [ ]:
base.loc[base['price'] > 350000]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000,control,coupe,1980,manuell,277,andere,20000,12,benzin,bmw,nein
10649,420000,control,coupe,2004,manuell,483,911,50000,4,benzin,porsche,nein
14663,11111111,control,coupe,2003,manuell,64,polo,150000,2,benzin,volkswagen,NaN
16889,1000000,control,kombi,1998,NaN,0,mondeo,150000,0,benzin,ford,ja
20143,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
364171,3890000,test,coupe,2006,NaN,799,NaN,5000,7,NaN,sonstige_autos,nein
365461,599000,control,coupe,1980,manuell,377,andere,5000,3,benzin,bmw,nein
366653,99999999,control,cabrio,1996,manuell,192,3er,150000,0,NaN,bmw,NaN
366861,3895000,test,coupe,2006,NaN,799,NaN,5000,4,benzin,sonstige_autos,nein
367041,1600000,test,coupe,2005,NaN,625,NaN,10000,4,benzin,sonstige_autos,nein

In [ ]:
base = base.loc[base['price'] < 350000]

In [ ]:
base.shape

(359291, 12)

In [ ]:
base.loc[pd.isnull(base['vehicleType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
22,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
base['vehicleType'].value_counts()

vehicleType
limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: count, dtype: int64

In [ ]:
base['vehicleType'].mode()

0    limousine
Name: vehicleType, dtype: object

In [ ]:
base.loc[pd.isnull(base['gearbox'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
32,245,test,limousine,1994,NaN,0,golf,150000,2,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
base['gearbox'].value_counts()

gearbox
manuell      266547
automatik     75508
Name: count, dtype: int64

In [ ]:
base.loc[pd.isnull(base['model'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
base['model'].value_counts()

model
golf               28989
andere             25560
3er                19905
polo               12604
corsa              12149
                   ...
serie_2                8
rangerover             6
serie_3                3
serie_1                1
discovery_sport        1
Name: count, Length: 251, dtype: int64

In [ ]:
base.loc[pd.isnull(base['fuelType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
13,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371496,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
base['fuelType'].value_counts()

fuelType
benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: count, dtype: int64

In [ ]:
base.loc[pd.isnull(base['notRepairedDamage'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
12,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371507,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN
371514,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN
371515,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN

In [ ]:
base['notRepairedDamage'].value_counts()

notRepairedDamage
nein    259301
ja       34004
Name: count, dtype: int64

In [ ]:
valores = {'vehicleType': 'limousine',
           'gearbox': 'manuell',
           'model': 'golf',
           'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}

In [ ]:
base = base.fillna(value = valores)

In [ ]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,limousine,1993,manuell,0,golf,150000,0,benzin,volkswagen,nein
1,18300,test,coupe,2011,manuell,190,golf,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,nein
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2200,test,limousine,2005,manuell,0,golf,20000,1,benzin,sonstige_autos,nein
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,nein
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [ ]:
base.isnull().sum()

price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dtype: int64

In [ ]:
base.columns

Index(['price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'notRepairedDamage'],
      dtype='object')

In [ ]:
X = base.iloc[:, 1:12].values
X

array([['test', 'limousine', 1993, ..., 'benzin', 'volkswagen', 'nein'],
       ['test', 'coupe', 2011, ..., 'diesel', 'audi', 'ja'],
       ['test', 'suv', 2004, ..., 'diesel', 'jeep', 'nein'],
       ...,
       ['test', 'bus', 1996, ..., 'diesel', 'volkswagen', 'nein'],
       ['test', 'kombi', 2002, ..., 'diesel', 'volkswagen', 'nein'],
       ['control', 'limousine', 2013, ..., 'benzin', 'bmw', 'nein']],
      dtype=object)

In [ ]:
y = base.iloc[:, 0].values
y

array([  480, 18300,  9800, ...,  9200,  3400, 28990])

In [ ]:
# volkswagen - 0
# bmw        - 1
# audi       - 2

# 1 0 0
# 0 1 0
# 0 0 1
base['brand'].value_counts()

brand
volkswagen        76755
bmw               38982
opel              38557
mercedes_benz     34498
audi              31884
ford              24761
renault           17367
peugeot           10777
fiat               9339
seat               6815
skoda              5572
mazda              5529
smart              5159
citroen            5038
nissan             4893
toyota             4616
hyundai            3585
mini               3354
sonstige_autos     3331
volvo              3229
mitsubishi         2956
honda              2726
kia                2494
suzuki             2274
alfa_romeo         2250
porsche            2154
chevrolet          1791
chrysler           1373
dacia               889
jeep                784
daihatsu            774
land_rover          759
subaru              746
jaguar              603
daewoo              530
saab                516
trabant             489
lancia              467
rover               462
lada                213
Name: count, dtype: int64

In [ ]:
base.columns

Index(['price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'notRepairedDamage'],
      dtype='object')

In [ ]:
onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [0, 1, 3, 5, 8, 9, 10])], remainder='passthrough')

In [ ]:
X = onehotencoder.fit_transform(X).toarray()
X

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]])

In [ ]:
base.shape

(359291, 12)

In [ ]:
X.shape

(359291, 316)

In [ ]:
(316 + 1) / 2

158.5

In [ ]:
regressor = Sequential([
    tf.keras.layers.InputLayer(shape = (316,)),
    tf.keras.layers.Dense(units = 158, activation = 'relu'),
    tf.keras.layers.Dense(units = 158, activation = 'relu'),
    tf.keras.layers.Dense(units = 1, activation = 'linear')
])

In [ ]:
regressor.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 158)                 │          50,086 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 158)                 │          25,122 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │             159 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 75,367 (294.40 KB)

 Trainable params: 75,367 (294.40 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# A
# real: 12.000
# previsão: 13.000

# B
# real: 11.500
# previsão: 10.000
12000 - 13000, 11500 - 10000
(abs(12000 - 13000) + abs(11500 - 10000)) / 2

1250.0

In [ ]:
regressor.compile(loss = 'mean_absolute_error', optimizer = 'adam', metrics = ['mean_absolute_error'])

In [ ]:
regressor.fit(X, y, batch_size = 300, epochs = 100)

Epoch 1/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 4374.8477 - mean_absolute_error: 4374.8477
Epoch 2/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 3435.1978 - mean_absolute_error: 3435.1978
Epoch 3/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 3188.7937 - mean_absolute_error: 3188.7937
Epoch 4/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2972.9241 - mean_absolute_error: 2972.9241
Epoch 5/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 2869.0256 - mean_absolute_error: 2869.0256
Epoch 6/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2792.5352 - mean_absolute_error: 2792.5352
Epoch 7/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2755.5708 - mean_absolute_error: 2755.5708
Epoch 8/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2710.6829 - mean_absolute_error: 2710.6829
Epoch 9/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2642.3862 - mean_absolute_error: 2642.3862
Epoch 10/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2629.9407 - mean_absolute_error: 2629.9407
Epoch 11/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2573.0044 - mean_absolute_error: 2573.0044
Epoch 12/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2545.3201 - mean_absolute_error: 2545.3201
Epoch 13/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 2512.3103 - mean_absolute_error: 2512.3103
Epoch 14/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2478.0103 - mean_absolute_error: 2478.0103
Epoch 15/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2479.2393 - mean_absolute_error: 2479.2393
Epoch 16/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 2436.0513 - mean_absolute_error: 2436.0513
Epoch 17/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 2442.2991 - mean_absolute_error: 2442.2991
Epoch 18/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 2432.2229 - mean_absolute_error: 2432.2229
Epoch 19/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2428.5374 - mean_absolute_error: 2428.5374
Epoch 20/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2412.0132 - mean_absolute_error: 2412.0132
Epoch 21/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 2402.4229 - mean_absolute_error: 2402.4229
Epoch 22/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2409.0444 - mean_absolute_error: 2409.0444
Epoch 23/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 2427.4966 - mean_absolute_error: 2427.4966
Epoch 24/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2398.4622 - mean_absolute_error: 2398.4622
Epoch 25/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2383.3472 - mean_absolute_error: 2383.3472
Epoch 26/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2393.6890 - mean_absolute_error: 2393.6890
Epoch 27/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2397.0881 - mean_absolute_error: 2397.0881
Epoch 28/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2379.2356 - mean_absolute_error: 2379.2356
Epoch 29/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2385.4773 - mean_absolute_error: 2385.4775
Epoch 30/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2372.1780 - mean_absolute_error: 2372.1780
Epoch 31/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2358.9475 - mean_absolute_error: 2358.9475
Epoch 32/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2373.6375 - mean_absolute_error: 2373.6375
Epoch 33/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2356.0093 - mean_absolute_error: 2356.0093
Epoch 34/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2350.4539 - mean_absolute_error: 2350.4539
Epoch 35/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2393.3123 - mean_absolute_error: 2393.3123
Epoch 36/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2343.0295 - mean_absolute_error: 2343.0295
Epoch 37/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2337.5391 - mean_absolute_error: 2337.5388
Epoch 38/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2353.8711 - mean_absolute_error: 2353.8711
Epoch 39/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2327.1511 - mean_absolute_error: 2327.1511
Epoch 40/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2342.1418 - mean_absolute_error: 2342.1418
Epoch 41/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2344.0991 - mean_absolute_error: 2344.0989
Epoch 42/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2328.7061 - mean_absolute_error: 2328.7061
Epoch 43/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2326.1377 - mean_absolute_error: 2326.1377
Epoch 44/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 2320.8284 - mean_absolute_error: 2320.8284
Epoch 45/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2319.7166 - mean_absolute_error: 2319.7166
Epoch 46/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2326.6274 - mean_absolute_error: 2326.6274
Epoch 47/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 2334.5793 - mean_absolute_error: 2334.5793
Epoch 48/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 2314.6985 - mean_absolute_error: 2314.6985
Epoch 49/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 2295.2144 - mean_absolute_error: 2295.2144
Epoch 50/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2324.3711 - mean_absolute_error: 2324.3711
Epoch 51/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 2308.4692 - mean_absolute_error: 2308.4692
Epoch 52/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2302.4038 - mean_absolute_error: 2302.4038
Epoch 53/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2287.7456 - mean_absolute_error: 2287.7456
Epoch 54/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2293.3511 - mean_absolute_error: 2293.3511
Epoch 55/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2288.2261 - mean_absolute_error: 2288.2261
Epoch 56/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2296.0911 - mean_absolute_error: 2296.0908
Epoch 57/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2296.3650 - mean_absolute_error: 2296.3650
Epoch 58/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2279.1018 - mean_absolute_error: 2279.1018
Epoch 59/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2285.2341 - mean_absolute_error: 2285.2341
Epoch 60/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2306.3271 - mean_absolute_error: 2306.3271
Epoch 61/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2270.5740 - mean_absolute_error: 2270.5740
Epoch 62/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2284.7769 - mean_absolute_error: 2284.7769
Epoch 63/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2277.1760 - mean_absolute_error: 2277.1760
Epoch 64/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2284.4031 - mean_absolute_error: 2284.4031
Epoch 65/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2293.1489 - mean_absolute_error: 2293.1489
Epoch 66/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2281.5562 - mean_absolute_error: 2281.5562
Epoch 67/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2280.2847 - mean_absolute_error: 2280.2847
Epoch 68/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 2249.4587 - mean_absolute_error: 2249.4587
Epoch 69/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2277.7131 - mean_absolute_error: 2277.7131
Epoch 70/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2274.3057 - mean_absolute_error: 2274.3057
Epoch 71/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2258.1052 - mean_absolute_error: 2258.1052
Epoch 72/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2271.6538 - mean_absolute_error: 2271.6538
Epoch 73/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2278.7695 - mean_absolute_error: 2278.7695
Epoch 74/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2261.7961 - mean_absolute_error: 2261.7961
Epoch 75/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 2272.1096 - mean_absolute_error: 2272.1094
Epoch 76/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2254.2458 - mean_absolute_error: 2254.2458
Epoch 77/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2244.2737 - mean_absolute_error: 2244.2737
Epoch 78/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2264.2881 - mean_absolute_error: 2264.2881
Epoch 79/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2270.6763 - mean_absolute_error: 2270.6763
Epoch 80/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2258.1423 - mean_absolute_error: 2258.1423
Epoch 81/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 2238.2241 - mean_absolute_error: 2238.2241
Epoch 82/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2249.6509 - mean_absolute_error: 2249.6509
Epoch 83/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2255.8501 - mean_absolute_error: 2255.8501
Epoch 84/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2251.1721 - mean_absolute_error: 2251.1721
Epoch 85/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2230.8577 - mean_absolute_error: 2230.8577
Epoch 86/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2228.0007 - mean_absolute_error: 2228.0007
Epoch 87/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 2244.0715 - mean_absolute_error: 2244.0715
Epoch 88/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 2242.1628 - mean_absolute_error: 2242.1628
Epoch 89/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 2224.4480 - mean_absolute_error: 2224.4480
Epoch 90/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2246.1204 - mean_absolute_error: 2246.1204
Epoch 91/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 2230.4836 - mean_absolute_error: 2230.4836
Epoch 92/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2249.9619 - mean_absolute_error: 2249.9619
Epoch 93/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2227.2747 - mean_absolute_error: 2227.2747
Epoch 94/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2228.9131 - mean_absolute_error: 2228.9131
Epoch 95/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 2229.7285 - mean_absolute_error: 2229.7285
Epoch 96/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 2237.6487 - mean_absolute_error: 2237.6487
Epoch 97/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 2211.3264 - mean_absolute_error: 2211.3264
Epoch 98/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 2236.8638 - mean_absolute_error: 2236.8638
Epoch 99/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 2231.1726 - mean_absolute_error: 2231.1726
Epoch 100/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 2233.1472 - mean_absolute_error: 2233.1472

In [ ]:
X.shape

(359291, 316)

In [ ]:
previsoes = regressor.predict(X)

11228/11228 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

In [ ]:
previsoes

array([[ 1650.7913],
       [11537.803 ],
       [13653.87  ],
       ...,
       [ 6755.616 ],
       [ 3987.3774],
       [25912.53  ]], dtype=float32)

In [ ]:
y

array([  480, 18300,  9800, ...,  9200,  3400, 28990])

In [ ]:
y.mean()

5916.833945186492

In [ ]:
previsoes.mean()

5876.22